
services:

  mysql:
    container_name: mysql
    image: mysql:9.1
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ccs-tracking:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    command: dotnet run
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - ./:/app

volumes:
  ccs-tracking:
